version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: submodule update and execute
          command: |
            git submodule init
            git submodule update
      - run:
          name: update-npm
          command: 'sudo npm i -g npm@latest'
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Project
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - run:
          name: Check dist/iotajapan
          command: ls -la dist/iotajapan
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      # - run: yarn test
  deploy:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: submodule update and execute
          command: |
            git submodule init
            git submodule update
      - run:
          command: 'sudo npm i -g npm@latest'
      - run: npm i
      - run: git config user.name $GITHUB_NAME
      - run: git config user.email $GITHUB_EMAIL
      - run: npm run build
      - run:
          name: Check dist/iotajapan
          command: ls -la dist/iotajapan
      - run:
          name: Check dist
          command: ls -la dist
      - run:
          command: |
            cp dist/CNAME dist/iotajapan/
            cp dist/README.md dist/iotajapan/
            echo 'gitdir: ../../.git/modules/dist/iotajapan' > dist/iotajapan/.git
            cp dist/.gitignore dist/iotajapan/
            cd dist/iotajapan
            git add .
            msg="rebuilding site `date`"
            if [ $# -eq 1 ]
              then msg="$1"
            fi
            git commit -m "$msg"
            git push origin HEAD:master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
