version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: submodule update and execute
          command: |
            git submodule init
            git submodule update
      - run:
          name: update-npm
          command: 'sudo npm i -g npm@latest'
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Project
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run build
      - run:
          name: Check dist
          command: ls -la dist/iotajapan
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      # - run: yarn test
  deploy:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: submodule update and execute
          command: |
            git submodule init
            git submodule update
      - run:
          command: 'sudo npm i -g npm@latest'
      - run: npm i
      - run: git config user.name $GITHUB_NAME
      - run: git config user.email $GITHUB_EMAIL
      - run: bash deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
